# Generated by Django 3.1.7 on 2021-03-30 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appraisal', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_ID', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15, verbose_name='first name')),
                ('last_name', models.CharField(max_length=15, verbose_name='last name')),
                ('email', models.CharField(max_length=30, verbose_name='email')),
                ('contact', models.CharField(max_length=20, verbose_name='contact')),
                ('adress', models.TextField()),
                ('hire_date', models.DateField(verbose_name='hire date')),
                ('is_activte', models.BooleanField(default=True, verbose_name='is active')),
                ('department_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('manager_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.manager')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
